# 游戏基本信息
game:
  version: "2.0.0-webcli"

# AI配置
ai:
  provider: "kimi"
  api_key: "sk-kJo5gCMv0QKQqHfbHCdqpY5DBpqzQCrfLpHmih96HlMhr10T"  # 请替换为您的API密钥
  model: "kimi-k2-0711-preview"
  api_base_url: "https://api.moonshot.cn/v1"

# 游戏设置
game_settings:
  max_response_length: 500
  default_mood: 0.5
  debug_mode: false

# 服务器配置
server:
  host: "0.0.0.0"
  port: 8080
  session_timeout: 3600

# 环境变量覆盖配置（这些值会被环境变量覆盖）
# API_KEY, DEBUG_MODE, SERVER_PORT